#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demostrate using the hello_hybrid.c example
# how to compile and run a HYBRID MPI/OpenMP code on Magnus in the 
# Cray Environment. 
# This is a mixed-mode job which includes both MPI and OpenMP.
# hello_hybrid.c code is taken from
# http://www.slac.stanford.edu/comp/unix/farm/mpi_and_openmp.html
# To run this code, we need to specify:
# the total number of MPI tasks,
# the number of MPI tasks per node,
# the number of MPI tasks per socket, and
# the number of threads for each MPI task. 
# This information is located under hello_hybrid_cray.slurm
# You can edit the SLURM as: emacs hello_hybrid_cray.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# Then, we set the total number of threads to 12
# export OMP_NUM_THREADS=12
# To launch a job, we specify to aprun 4 MPI tasks (-n 4)
# with 4 MPI tasks per node (-N 2),
# with 2 MPI tasks per socket or NUMA region (-S 1)
# and each MPI tasks have 12 threads. (-d 12)
# Therefore, the aprun command looks like:
# aprun -n 4 -N 2 -S 1 -d 12 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_hybdrid.c code with Cray Environment
cc -O2 -h omp hello_hybrid.c -o hello_hybrid_cray
echo "hello_hybrid.c was compiled using:"
echo "cc -O2 -h omp hello_hybrid.c -o hello_hybrid_cray"
echo " "


# To submit the job to Magnus
sbatch hello_hybrid_cray.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_hello_hybrid_c_cray/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/hello_hybrid_c_cray_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/hello_hybrid_c_cray_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat hello_hybrid_c_cray.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
